version: 2

jobs:
    toxify:

        docker:
            - image: python:3.7

        steps:

            - checkout

            - run: pip install tox && tox

            - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
