version: 2

jobs:
    toxify:

        docker:
            - image: python:3.7

        steps:

            - checkout

            - run: pip install tox && tox
    coverage:
        steps:
            -run : codecov

    

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
      - coverage
        
