version: 2

jobs:
    toxify:

        docker:
            - image: python:3.7

        steps:

            - checkout

            - run: pip install tox && tox

            - run: codecov --required || (sleep 5 && codecov --required) || (sleep 5 && codecov --required) || (sleep 5 && codecov --required) || (sleep 5 && codecov --required)

workflows:
  version: 2

  myproj:
    jobs:
      - toxify
